package shell

import (
	"os"
	"path/filepath"
	"strings"
)

// DetectShellConfig attempts to detect the user's shell config file
func DetectShellConfig() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}

	// Check SHELL environment variable
	shell := os.Getenv("SHELL")

	// Common shell configs in priority order
	configs := []string{}

	if strings.Contains(shell, "zsh") {
		configs = append(configs, ".zshrc", ".zprofile")
	} else if strings.Contains(shell, "bash") {
		configs = append(configs, ".bashrc", ".bash_profile", ".profile")
	}

	// Add fallbacks
	configs = append(configs, ".zshrc", ".bashrc", ".bash_profile", ".profile")

	// Check which exists
	for _, config := range configs {
		path := filepath.Join(home, config)
		if _, err := os.Stat(path); err == nil {
			return config
		}
	}

	// Default to .zshrc (macOS default)
	return ".zshrc"
}

// GenerateAliasCommands generates shell alias commands for the given tools
func GenerateAliasCommands(tools []string) string {
	home, _ := os.UserHomeDir()
	wrapperDir := filepath.Join(home, ".jtpck")

	var cmds strings.Builder
	for _, tool := range tools {
		wrapperPath := filepath.Join(wrapperDir, tool+"-wrapper")
		cmds.WriteString("alias ")
		cmds.WriteString(tool)
		cmds.WriteString("='")
		cmds.WriteString(wrapperPath)
		cmds.WriteString("'\n")
	}
	return cmds.String()
}

// InstallAliases appends aliases to shell config with backup
func InstallAliases(tools []string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}

	shellConfig := DetectShellConfig()
	configPath := filepath.Join(home, shellConfig)

	// Check if config file exists, create if not
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		// Create empty config file
		if err := os.WriteFile(configPath, []byte(""), 0644); err != nil {
			return err
		}
	}

	// Backup existing config
	backupPath := configPath + ".jtpck-backup"
	input, err := os.ReadFile(configPath)
	if err != nil {
		return err
	}
	if err := os.WriteFile(backupPath, input, 0644); err != nil {
		return err
	}

	// Read current config
	content := string(input)

	// Check if JTPCK aliases already exist
	if strings.Contains(content, "# JTPCK Telemetry Aliases") {
		// Remove old JTPCK section
		lines := strings.Split(content, "\n")
		var newLines []string
		skipUntilEnd := false
		for _, line := range lines {
			if strings.Contains(line, "# JTPCK Telemetry Aliases - START") {
				skipUntilEnd = true
			}
			if !skipUntilEnd {
				newLines = append(newLines, line)
			}
			if strings.Contains(line, "# JTPCK Telemetry Aliases - END") {
				skipUntilEnd = false
			}
		}
		content = strings.Join(newLines, "\n")
	}

	// Generate alias commands
	aliasCommands := GenerateAliasCommands(tools)

	// Append new JTPCK section
	var sb strings.Builder
	sb.WriteString(strings.TrimRight(content, "\n"))
	sb.WriteString("\n\n")
	sb.WriteString("# JTPCK Telemetry Aliases - START\n")
	sb.WriteString("# Auto-generated by JTPCK installer\n")
	sb.WriteString(aliasCommands)
	sb.WriteString("# JTPCK Telemetry Aliases - END\n")

	// Write updated config
	return os.WriteFile(configPath, []byte(sb.String()), 0644)
}
