version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: jtpck
    main: ./JTPCK.go
    binary: jtpck
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CLAUDE.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: jtpck
    repository:
      owner: jessewaites
      name: homebrew-jtpck
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    homepage: https://github.com/jessewaites/jtpck-installer
    description: CLI tool for configuring OpenTelemetry in Claude Code, Codex, and Gemini CLI
    license: MIT
    install: |
      bin.install "jtpck"
    test: |
      system "#{bin}/jtpck", "--version"
